<?php

function fotosEquipamentos()
{
    return [
        // =========================
        // BLOCO A
        // =========================
        'A01' => [
            'computador' => 'assets/img/a01/computador.jpg',
            'monitor' => 'assets/img/monitor.jpeg',
            'teclado' => 'assets/img/a01/teclado.jpg',
            'mouse' => 'assets/img/a01/mouse.jpg',
            'estabilizador' => 'assets/img/a01/estabilizador.jpg',
            'som' => 'assets/img/a01/som.jpg',
            'projetor' => 'assets/img/a01/projetor.jpg',
            'lousa' => 'assets/img/a01/lousa.jpg',
        ],
        'A02' => [
            'computador' => 'assets/img/a02/computador.jpg',
            'monitor' => 'assets/img/a02/monitor.jpg',
            'teclado' => 'assets/img/a02/teclado.jpg',
            'mouse' => 'assets/img/a02/mouse.jpg',
            'estabilizador' => 'assets/img/a02/estabilizador.jpg',
            'som' => 'assets/img/a02/som.jpg',
            'projetor' => 'assets/img/a02/projetor.jpg',
            'lousa' => 'assets/img/a02/lousa.jpg',
        ],
        'A03' => [
            'computador' => 'assets/img/a03/computador.jpg',
            'monitor' => 'assets/img/a03/monitor.jpg',
            'teclado' => 'assets/img/a03/teclado.jpg',
            'mouse' => 'assets/img/a03/mouse.jpg',
            'estabilizador' => 'assets/img/a03/estabilizador.jpg',
            'som' => 'assets/img/a03/som.jpg',
            'projetor' => 'assets/img/a03/projetor.jpg',
            'lousa' => 'assets/img/a03/lousa.jpg',
        ],
        'A04' => [
            'computador' => 'assets/img/a04/computador.jpg',
            'monitor' => 'assets/img/a04/monitor.jpg',
            'teclado' => 'assets/img/a04/teclado.jpg',
            'mouse' => 'assets/img/a04/mouse.jpg',
            'estabilizador' => 'assets/img/a04/estabilizador.jpg',
            'som' => 'assets/img/a04/som.jpg',
            'projetor' => 'assets/img/a04/projetor.jpg',
            'lousa' => 'assets/img/a04/lousa.jpg',
        ],
        'A05' => [
            'computador' => 'assets/img/a05/computador.jpg',
            'monitor' => 'assets/img/a05/monitor.jpg',
            'teclado' => 'assets/img/a05/teclado.jpg',
            'mouse' => 'assets/img/a05/mouse.jpg',
            'estabilizador' => 'assets/img/a05/estabilizador.jpg',
            'som' => 'assets/img/a05/som.jpg',
            'projetor' => 'assets/img/a05/projetor.jpg',
            'lousa' => 'assets/img/a05/lousa.jpg',
        ],
        'A06' => [
            'computador' => 'assets/img/a06/computador.jpg',
            'monitor' => 'assets/img/a06/monitor.jpg',
            'teclado' => 'assets/img/a06/teclado.jpg',
            'mouse' => 'assets/img/a06/mouse.jpg',
            'estabilizador' => 'assets/img/a06/estabilizador.jpg',
            'som' => 'assets/img/a06/som.jpg',
            'projetor' => 'assets/img/a06/projetor.jpg',
            'lousa' => 'assets/img/a06/lousa.jpg',
        ],
        'A07' => [
            'computador' => 'assets/img/a07/computador.jpg',
            'monitor' => 'assets/img/a07/monitor.jpg',
            'teclado' => 'assets/img/a07/teclado.jpg',
            'mouse' => 'assets/img/a07/mouse.jpg',
            'estabilizador' => 'assets/img/a07/estabilizador.jpg',
            'som' => 'assets/img/a07/som.jpg',
            'projetor' => 'assets/img/a07/projetor.jpg',
            'lousa' => 'assets/img/a07/lousa.jpg',
        ],
        'A08' => [
            'computador' => 'assets/img/a08/computador.jpg',
            'monitor' => 'assets/img/a08/monitor.jpg',
            'teclado' => 'assets/img/a08/teclado.jpg',
            'mouse' => 'assets/img/a08/mouse.jpg',
            'estabilizador' => 'assets/img/a08/estabilizador.jpg',
            'som' => 'assets/img/a08/som.jpg',
            'projetor' => 'assets/img/a08/projetor.jpg',
            'lousa' => 'assets/img/a08/lousa.jpg',
        ],
        'A09' => [
            'computador' => 'assets/img/a09/computador.jpg',
            'monitor' => 'assets/img/a09/monitor.jpg',
            'teclado' => 'assets/img/a09/teclado.jpg',
            'mouse' => 'assets/img/a09/mouse.jpg',
            'estabilizador' => 'assets/img/a09/estabilizador.jpg',
            'som' => 'assets/img/a09/som.jpg',
            'projetor' => 'assets/img/a09/projetor.jpg',
            'lousa' => 'assets/img/a09/lousa.jpg',
        ],

        // =========================
        // BLOCO C
        // =========================
        'C01' => [
            'computador' => 'assets/img/c01/computador.jpg',
            'monitor' => 'assets/img/c01/monitor.jpg',
            'teclado' => 'assets/img/c01/teclado.jpg',
            'mouse' => 'assets/img/c01/mouse.jpg',
            'estabilizador' => 'assets/img/c01/estabilizador.jpg',
            'som' => 'assets/img/c01/som.jpg',
            'projetor' => 'assets/img/c01/projetor.jpg',
            'lousa' => 'assets/img/c01/lousa.jpg',
        ],
        'C02' => [
            'computador' => 'assets/img/c02/computador.jpg',
            'monitor' => 'assets/img/c02/monitor.jpg',
            'teclado' => 'assets/img/c02/teclado.jpg',
            'mouse' => 'assets/img/c02/mouse.jpg',
            'estabilizador' => 'assets/img/c02/estabilizador.jpg',
            'som' => 'assets/img/c02/som.jpg',
            'projetor' => 'assets/img/c02/projetor.jpg',
            'lousa' => 'assets/img/c02/lousa.jpg',
        ],
        'C03' => [
            'computador' => 'assets/img/c03/computador.jpg',
            'monitor' => 'assets/img/c03/monitor.jpg',
            'teclado' => 'assets/img/c03/teclado.jpg',
            'mouse' => 'assets/img/c03/mouse.jpg',
            'estabilizador' => 'assets/img/c03/estabilizador.jpg',
            'som' => 'assets/img/c03/som.jpg',
            'projetor' => 'assets/img/c03/projetor.jpg',
            'lousa' => 'assets/img/c03/lousa.jpg',
        ],
        'C04' => [
            'computador' => 'assets/img/c04/computador.jpg',
            'monitor' => 'assets/img/c04/monitor.jpg',
            'teclado' => 'assets/img/c04/teclado.jpg',
            'mouse' => 'assets/img/c04/mouse.jpg',
            'estabilizador' => 'assets/img/c04/estabilizador.jpg',
            'som' => 'assets/img/c04/som.jpg',
            'projetor' => 'assets/img/c04/projetor.jpg',
            'lousa' => 'assets/img/c04/lousa.jpg',
        ],
        'C05' => [
            'computador' => 'assets/img/c05/computador.jpg',
            'monitor' => 'assets/img/c05/monitor.jpg',
            'teclado' => 'assets/img/c05/teclado.jpg',
            'mouse' => 'assets/img/c05/mouse.jpg',
            'estabilizador' => 'assets/img/c05/estabilizador.jpg',
            'som' => 'assets/img/c05/som.jpg',
            'projetor' => 'assets/img/c05/projetor.jpg',
            'lousa' => 'assets/img/c05/lousa.jpg',
        ],
        'C06' => [
            'computador' => 'assets/img/c06/computador.jpg',
            'monitor' => 'assets/img/c06/monitor.jpg',
            'teclado' => 'assets/img/c06/teclado.jpg',
            'mouse' => 'assets/img/c06/mouse.jpg',
            'estabilizador' => 'assets/img/c06/estabilizador.jpg',
            'som' => 'assets/img/c06/som.jpg',
            'projetor' => 'assets/img/c06/projetor.jpg',
            'lousa' => 'assets/img/c06/lousa.jpg',
        ],
        'C07' => [
            'computador' => 'assets/img/c07/computador.jpg',
            'monitor' => 'assets/img/c07/monitor.jpg',
            'teclado' => 'assets/img/c07/teclado.jpg',
            'mouse' => 'assets/img/c07/mouse.jpg',
            'estabilizador' => 'assets/img/c07/estabilizador.jpg',
            'som' => 'assets/img/c07/som.jpg',
            'projetor' => 'assets/img/c07/projetor.jpg',
            'lousa' => 'assets/img/c07/lousa.jpg',
        ],
        'C08' => [
            'computador' => 'assets/img/c08/computador.jpg',
            'monitor' => 'assets/img/c08/monitor.jpg',
            'teclado' => 'assets/img/c08/teclado.jpg',
            'mouse' => 'assets/img/c08/mouse.jpg',
            'estabilizador' => 'assets/img/c08/estabilizador.jpg',
            'som' => 'assets/img/c08/som.jpg',
            'projetor' => 'assets/img/c08/projetor.jpg',
            'lousa' => 'assets/img/c08/lousa.jpg',
        ],
        'C09' => [
            'computador' => 'assets/img/c09/computador.jpg',
            'monitor' => 'assets/img/c09/monitor.jpg',
            'teclado' => 'assets/img/c09/teclado.jpg',
            'mouse' => 'assets/img/c09/mouse.jpg',
            'estabilizador' => 'assets/img/c09/estabilizador.jpg',
            'som' => 'assets/img/c09/som.jpg',
            'projetor' => 'assets/img/c09/projetor.jpg',
            'lousa' => 'assets/img/c09/lousa.jpg',
        ],
        'EI' => [
            'computador' => 'assets/img/ei/computador.jpg',
            'monitor' => 'assets/img/ei/monitor.jpg',
            'teclado' => 'assets/img/ei/teclado.jpg',
            'mouse' => 'assets/img/ei/mouse.jpg',
            'estabilizador' => 'assets/img/ei/estabilizador.jpg',
            'som' => 'assets/img/ei/som.jpg',
            'projetor' => 'assets/img/ei/projetor.jpg',
            'lousa' => 'assets/img/ei/lousa.jpg',
        ],

        // =========================
        // BLOCO D
        // =========================
        'D01' => [
            'computador' => 'assets/img/d01/computador.jpg',
            'monitor' => 'assets/img/d01/monitor.jpg',
            'teclado' => 'assets/img/d01/teclado.jpg',
            'mouse' => 'assets/img/d01/mouse.jpg',
            'estabilizador' => 'assets/img/d01/estabilizador.jpg',
            'som' => 'assets/img/d01/som.jpg',
            'projetor' => 'assets/img/d01/projetor.jpg',
            'lousa' => 'assets/img/d01/lousa.jpg',
        ],
        'D02' => [
            'computador' => 'assets/img/d02/computador.jpg',
            'monitor' => 'assets/img/d02/monitor.jpg',
            'teclado' => 'assets/img/d02/teclado.jpg',
            'mouse' => 'assets/img/d02/mouse.jpg',
            'estabilizador' => 'assets/img/d02/estabilizador.jpg',
            'som' => 'assets/img/d02/som.jpg',
            'projetor' => 'assets/img/d02/projetor.jpg',
            'lousa' => 'assets/img/d02/lousa.jpg',
        ],
        'D03' => [
            'computador' => 'assets/img/d03/computador.jpg',
            'monitor' => 'assets/img/d03/monitor.jpg',
            'teclado' => 'assets/img/d03/teclado.jpg',
            'mouse' => 'assets/img/d03/mouse.jpg',
            'estabilizador' => 'assets/img/d03/estabilizador.jpg',
            'som' => 'assets/img/d03/som.jpg',
            'projetor' => 'assets/img/d03/projetor.jpg',
            'lousa' => 'assets/img/d03/lousa.jpg',
        ],

        // =========================
        // BLOCO E
        // =========================
        'E01' => [
            'computador' => 'assets/img/e01/computador.jpg',
            'monitor' => 'assets/img/e01/monitor.jpg',
            'teclado' => 'assets/img/e01/teclado.jpg',
            'mouse' => 'assets/img/e01/mouse.jpg',
            'estabilizador' => 'assets/img/e01/estabilizador.jpg',
            'som' => 'assets/img/e01/som.jpg',
            'projetor' => 'assets/img/e01/projetor.jpg',
            'lousa' => 'assets/img/e01/lousa.jpg',
        ],
        'E02' => [
            'computador' => 'assets/img/e02/computador.jpg',
            'monitor' => 'assets/img/e02/monitor.jpg',
            'teclado' => 'assets/img/e02/teclado.jpg',
            'mouse' => 'assets/img/e02/mouse.jpg',
            'estabilizador' => 'assets/img/e02/estabilizador.jpg',
            'som' => 'assets/img/e02/som.jpg',
            'projetor' => 'assets/img/e02/projetor.jpg',
            'lousa' => 'assets/img/e02/lousa.jpg',
        ],
        'E03' => [
            'computador' => 'assets/img/e03/computador.jpg',
            'monitor' => 'assets/img/e03/monitor.jpg',
            'teclado' => 'assets/img/e03/teclado.jpg',
            'mouse' => 'assets/img/e03/mouse.jpg',
            'estabilizador' => 'assets/img/e03/estabilizador.jpg',
            'som' => 'assets/img/e03/som.jpg',
            'projetor' => 'assets/img/e03/projetor.jpg',
            'lousa' => 'assets/img/e03/lousa.jpg',
        ],
        'E04' => [
            'computador' => 'assets/img/e04/computador.jpg',
            'monitor' => 'assets/img/e04/monitor.jpg',
            'teclado' => 'assets/img/e04/teclado.jpg',
            'mouse' => 'assets/img/e04/mouse.jpg',
            'estabilizador' => 'assets/img/e04/estabilizador.jpg',
            'som' => 'assets/img/e04/som.jpg',
            'projetor' => 'assets/img/e04/projetor.jpg',
            'lousa' => 'assets/img/e04/lousa.jpg',
        ],
        'E05' => [
            'computador' => 'assets/img/e05/computador.jpg',
            'monitor' => 'assets/img/e05/monitor.jpg',
            'teclado' => 'assets/img/e05/teclado.jpg',
            'mouse' => 'assets/img/e05/mouse.jpg',
            'estabilizador' => 'assets/img/e05/estabilizador.jpg',
            'som' => 'assets/img/e05/som.jpg',
            'projetor' => 'assets/img/e05/projetor.jpg',
            'lousa' => 'assets/img/e05/lousa.jpg',
        ],
        'E06' => [
            'computador' => 'assets/img/e06/computador.jpg',
            'monitor' => 'assets/img/e06/monitor.jpg',
            'teclado' => 'assets/img/e06/teclado.jpg',
            'mouse' => 'assets/img/e06/mouse.jpg',
            'estabilizador' => 'assets/img/e06/estabilizador.jpg',
            'som' => 'assets/img/e06/som.jpg',
            'projetor' => 'assets/img/e06/projetor.jpg',
            'lousa' => 'assets/img/e06/lousa.jpg',
        ],
        'E07' => [
            'computador' => 'assets/img/e07/computador.jpg',
            'monitor' => 'assets/img/e07/monitor.jpg',
            'teclado' => 'assets/img/e07/teclado.jpg',
            'mouse' => 'assets/img/e07/mouse.jpg',
            'estabilizador' => 'assets/img/e07/estabilizador.jpg',
            'som' => 'assets/img/e07/som.jpg',
            'projetor' => 'assets/img/e07/projetor.jpg',
            'lousa' => 'assets/img/e07/lousa.jpg',
        ],
        'E08' => [
            'computador' => 'assets/img/e08/computador.jpg',
            'monitor' => 'assets/img/e08/monitor.jpg',
            'teclado' => 'assets/img/e08/teclado.jpg',
            'mouse' => 'assets/img/e08/mouse.jpg',
            'estabilizador' => 'assets/img/e08/estabilizador.jpg',
            'som' => 'assets/img/e08/som.jpg',
            'projetor' => 'assets/img/e08/projetor.jpg',
            'lousa' => 'assets/img/e08/lousa.jpg',
        ],
        'E09' => [
            'computador' => 'assets/img/e09/computador.jpg',
            'monitor' => 'assets/img/e09/monitor.jpg',
            'teclado' => 'assets/img/e09/teclado.jpg',
            'mouse' => 'assets/img/e09/mouse.jpg',
            'estabilizador' => 'assets/img/e09/estabilizador.jpg',
            'som' => 'assets/img/e09/som.jpg',
            'projetor' => 'assets/img/e09/projetor.jpg',
            'lousa' => 'assets/img/e09/lousa.jpg',
        ],
    ];
}

function fotoEquipamento($codigoSala, $nomeEquipamento)
{
    $fotos = fotosEquipamentos();
    $equipamento = strtolower($nomeEquipamento);

    return $fotos[$codigoSala][$equipamento] ?? '';
}

function obterCaminhoImagem($codigoSala, $nomeEquipamento)
{
    return fotoEquipamento($codigoSala, $nomeEquipamento);
}